// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyARx-F7i2ao6AsQ5TOJ4iGwhlc0BhyOtnw',
    appId: '1:192379409133:web:a384fb5764ec54c4fa32e4',
    messagingSenderId: '192379409133',
    projectId: 'doctor-appointment-dfe62',
    authDomain: 'doctor-appointment-dfe62.firebaseapp.com',
    databaseURL: 'https://doctor-appointment-dfe62-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'doctor-appointment-dfe62.appspot.com',
    measurementId: 'G-660BC7SCGY',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAjoi1ZeECP8wMRJsgEkqlpU8rc2MRDay8',
    appId: '1:192379409133:android:6c1dd14e18789a86fa32e4',
    messagingSenderId: '192379409133',
    projectId: 'doctor-appointment-dfe62',
    databaseURL: 'https://doctor-appointment-dfe62-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'doctor-appointment-dfe62.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDvVuVPWfC21SVrzN_I-U1Y1nnxK5vgZtM',
    appId: '1:192379409133:ios:37f8b7a262121b9afa32e4',
    messagingSenderId: '192379409133',
    projectId: 'doctor-appointment-dfe62',
    databaseURL: 'https://doctor-appointment-dfe62-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'doctor-appointment-dfe62.appspot.com',
    iosBundleId: 'com.example.medical',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDvVuVPWfC21SVrzN_I-U1Y1nnxK5vgZtM',
    appId: '1:192379409133:ios:c0fcacebbef9b8e9fa32e4',
    messagingSenderId: '192379409133',
    projectId: 'doctor-appointment-dfe62',
    databaseURL: 'https://doctor-appointment-dfe62-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'doctor-appointment-dfe62.appspot.com',
    iosBundleId: 'com.example.medical.RunnerTests',
  );
}
